[package]
name = "core"
version = "0.1.0"
edition = "2024"

[lib]
path = "lib.rs"

[dependencies]
shared = {path = "../shared"}
js-runtime = {path = "../js-runtime"}
graphics = {path = "../graphics"}
io = {path = "../io"}
audio = {path = "../audio"}
crossbeam-channel = { workspace = true }
lazy_static = "1.5.0"
futures = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }
tracing-android = { workspace = true }
tracing-subscriber = { workspace = true }
smallvec = { workspace = true }
deno_core = { workspace = true }
