//! Build script for js-runtime crate.
//!
//! Selects the per-architecture V8 startup snapshot and, when present, sets the
//! `migo_has_snapshot` cfg + `MIGO_SNAPSHOT_PATH` env so `snapshot.rs` can
//! `include_bytes!` it at compile time.
//!
//! # Why per-arch + Android-only
//!
//! A V8 startup snapshot serializes a live V8 heap, so it is bound to the
//! target **platform (OS + CPU arch)**: an android-aarch64 snapshot only loads
//! in an android-aarch64 V8, an android-x86_64 snapshot only in android-x86_64,
//! and a host-linux V8 cannot use either. Therefore:
//!
//!   * We keep one snapshot per Android ABI under `snapshots/SNAPSHOT-<arch>.bin`
//!     and pick the one matching `CARGO_CFG_TARGET_ARCH`. This makes a single
//!     multi-ABI `build-aar.sh` invocation embed the *correct* snapshot into
//!     each `.so` (embedding the wrong-arch snapshot would crash at startup with
//!     a V8 magic-number mismatch).
//!   * We only embed for `CARGO_CFG_TARGET_OS == "android"`. Host builds
//!     (`cargo test`, dev) always load extension JS from source — embedding an
//!     android snapshot into a host-linux binary would crash on load.
//!
//! Snapshots are generated by `migo-snapshot-gen` cross-compiled to the target
//! ABI and run on that ABI (emulator/device); see `crates/snapshot-gen`.

use std::path::Path;

fn main() {
    // Declare custom cfg for check-cfg lint.
    println!("cargo::rustc-check-cfg=cfg(migo_has_snapshot)");

    let target_os = std::env::var("CARGO_CFG_TARGET_OS").unwrap_or_default();
    let target_arch = std::env::var("CARGO_CFG_TARGET_ARCH").unwrap_or_default();
    let profile = std::env::var("PROFILE").unwrap_or_default();

    let snapshot_path = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("snapshots")
        .join(format!("SNAPSHOT-{target_arch}.bin"));

    // Re-run if this ABI's snapshot is added, removed, or regenerated.
    println!("cargo:rerun-if-changed={}", snapshot_path.display());

    // V8 startup snapshots only load in the matching android-<arch> V8. Never
    // embed for host (linux/macos) builds — they use the from-source path.
    if target_os != "android" {
        return;
    }

    if snapshot_path.exists() {
        println!("cargo:rustc-cfg=migo_has_snapshot");
        // Absolute path consumed by `include_bytes!(env!("MIGO_SNAPSHOT_PATH"))`.
        println!(
            "cargo:rustc-env=MIGO_SNAPSHOT_PATH={}",
            snapshot_path.display()
        );
        println!(
            "cargo:warning=V8 snapshot found for {} ({} bytes), embedding into binary",
            target_arch,
            std::fs::metadata(&snapshot_path)
                .map(|m| m.len())
                .unwrap_or(0)
        );
    } else if profile == "release" {
        println!(
            "cargo:warning=No V8 snapshot for {target_arch} at {} — release build will load JS from source (slower cold start)",
            snapshot_path.display()
        );
    }
}
