//! Build script for js-runtime crate.
//!
//! Selects and validates the per-architecture V8 startup snapshot. A matching
//! manifest sets `migo_has_snapshot` + `MIGO_SNAPSHOT_PATH`; stale or malformed
//! inputs leave the runtime on its source-JS fallback.
//!
//! # Why per-arch + Android-only
//!
//! A V8 startup snapshot serializes a live V8 heap, so it is bound to the
//! target **platform (OS + CPU arch)**: an android-aarch64 snapshot only loads
//! in an android-aarch64 V8, an android-x86_64 snapshot only in android-x86_64,
//! and a host-linux V8 cannot use either. Therefore:
//!
//!   * We keep one snapshot per Android ABI under `snapshots/SNAPSHOT-<arch>.bin`
//!     and pick the one matching `CARGO_CFG_TARGET_ARCH`. This makes a single
//!     multi-ABI `build-aar.sh` invocation embed the *correct* snapshot into
//!     each `.so` (embedding the wrong-arch snapshot would crash at startup with
//!     a V8 magic-number mismatch).
//!   * We only embed for `CARGO_CFG_TARGET_OS == "android"`. Host builds
//!     (`cargo test`, dev) always load extension JS from source — embedding an
//!     android snapshot into a host-linux binary would crash on load.
//!
//! Snapshots are generated by `migo-snapshot-gen` cross-compiled to the target
//! ABI and run on that ABI (emulator/device); see `crates/snapshot-gen`.

use std::{
    fs,
    path::{Path, PathBuf},
};

use serde_json::Value;
use sha2::{Digest, Sha256};

fn main() {
    // Declare custom cfg for check-cfg lint.
    println!("cargo::rustc-check-cfg=cfg(migo_has_snapshot)");

    let target_os = std::env::var("CARGO_CFG_TARGET_OS").unwrap_or_default();
    let target_arch = std::env::var("CARGO_CFG_TARGET_ARCH").unwrap_or_default();
    let profile = std::env::var("PROFILE").unwrap_or_default();

    let manifest_dir = Path::new(env!("CARGO_MANIFEST_DIR"));
    let repo_root = manifest_dir
        .ancestors()
        .nth(3)
        .expect("js-runtime must live under <repo>/engine/crates");
    let cargo_lock = repo_root.join("engine/Cargo.lock");
    let snapshot_path = manifest_dir
        .join("snapshots")
        .join(format!("SNAPSHOT-{target_arch}.bin"));
    let snapshot_manifest = PathBuf::from(format!("{}.manifest.json", snapshot_path.display()));

    let mut js_files = Vec::new();
    if let Err(error) = collect_js_files(manifest_dir, &mut js_files) {
        println!("cargo:warning=Failed to enumerate snapshot JS inputs: {error}");
    }
    js_files.sort();

    // Re-run if the snapshot or any input covered by its fingerprint changes.
    // Watching the directory recursively also catches newly-added JS files;
    // the per-file entries keep ordinary content changes explicit.
    println!("cargo:rerun-if-changed={}", manifest_dir.display());
    println!("cargo:rerun-if-changed={}", snapshot_path.display());
    println!("cargo:rerun-if-changed={}", snapshot_manifest.display());
    println!("cargo:rerun-if-changed={}", cargo_lock.display());
    for path in &js_files {
        println!("cargo:rerun-if-changed={}", path.display());
    }

    // V8 startup snapshots only load in the matching android-<arch> V8. Never
    // embed for host (linux/macos) builds — they use the from-source path.
    if target_os != "android" {
        return;
    }

    if snapshot_path.exists() {
        match validate_snapshot(
            repo_root,
            &snapshot_path,
            &snapshot_manifest,
            &cargo_lock,
            &js_files,
            &target_arch,
        ) {
            Ok(()) => {
                println!("cargo:rustc-cfg=migo_has_snapshot");
                // Absolute path consumed by `include_bytes!(env!("MIGO_SNAPSHOT_PATH"))`.
                println!(
                    "cargo:rustc-env=MIGO_SNAPSHOT_PATH={}",
                    snapshot_path.display()
                );
                println!(
                    "cargo:warning=Validated V8 snapshot for {} ({} bytes), embedding into binary",
                    target_arch,
                    fs::metadata(&snapshot_path).map(|m| m.len()).unwrap_or(0)
                );
            }
            Err(reason) => {
                println!(
                    "cargo:warning=Ignoring stale or invalid V8 snapshot for {target_arch}: {reason}; loading JS from source"
                );
            }
        }
    } else if profile == "release" {
        println!(
            "cargo:warning=No V8 snapshot for {target_arch} at {} — release build will load JS from source (slower cold start)",
            snapshot_path.display()
        );
    }
}

fn collect_js_files(dir: &Path, output: &mut Vec<PathBuf>) -> Result<(), std::io::Error> {
    for entry in fs::read_dir(dir)? {
        let entry = entry?;
        let path = entry.path();
        let file_type = entry.file_type()?;
        if file_type.is_dir() {
            collect_js_files(&path, output)?;
        } else if file_type.is_file() && path.extension().is_some_and(|ext| ext == "js") {
            output.push(path);
        }
    }
    Ok(())
}

fn validate_snapshot(
    repo_root: &Path,
    snapshot_path: &Path,
    manifest_path: &Path,
    cargo_lock: &Path,
    js_files: &[PathBuf],
    target_arch: &str,
) -> Result<(), String> {
    let manifest_bytes = fs::read(manifest_path)
        .map_err(|error| format!("manifest {} unavailable: {error}", manifest_path.display()))?;
    let manifest: Value = serde_json::from_slice(&manifest_bytes)
        .map_err(|error| format!("manifest JSON is invalid: {error}"))?;

    require_manifest_value(&manifest, "arch", target_arch)?;

    let expected_snapshot_hash = manifest_string(&manifest, "snapshot_sha256")?;
    let actual_snapshot_hash =
        sha256_file(snapshot_path).map_err(|error| format!("cannot hash snapshot: {error}"))?;
    require_equal_hash(
        "snapshot bytes",
        expected_snapshot_hash,
        &actual_snapshot_hash,
    )?;

    let expected_js_hash = manifest_string(&manifest, "js_sources_sha256")?;
    let actual_js_hash = snapshot_js_hash(repo_root, js_files)?;
    require_equal_hash("extension JS", expected_js_hash, &actual_js_hash)?;

    let expected_deno = manifest_string(&manifest, "deno_core_version")?;
    let actual_deno = deno_core_version(cargo_lock)?;
    if expected_deno != actual_deno {
        return Err(format!(
            "deno_core changed (manifest={expected_deno}, current={actual_deno})"
        ));
    }

    Ok(())
}

fn require_manifest_value(manifest: &Value, field: &str, expected: &str) -> Result<(), String> {
    let actual = manifest_string(manifest, field)?;
    if actual == expected {
        Ok(())
    } else {
        Err(format!(
            "manifest {field} mismatch (manifest={actual}, target={expected})"
        ))
    }
}

fn manifest_string<'a>(manifest: &'a Value, field: &str) -> Result<&'a str, String> {
    manifest
        .get(field)
        .and_then(Value::as_str)
        .ok_or_else(|| format!("manifest field {field:?} is missing or not a string"))
}

fn require_equal_hash(kind: &str, expected: &str, actual: &str) -> Result<(), String> {
    if expected == actual {
        Ok(())
    } else {
        Err(format!(
            "{kind} changed (manifest={}..., current={}...)",
            &expected[..expected.len().min(12)],
            &actual[..actual.len().min(12)],
        ))
    }
}

fn snapshot_js_hash(repo_root: &Path, js_files: &[PathBuf]) -> Result<String, String> {
    let mut outer = Sha256::new();
    for path in js_files {
        let relative = path
            .strip_prefix(repo_root)
            .map_err(|error| format!("JS path {} is outside repo: {error}", path.display()))?;
        let relative = relative.to_string_lossy().replace('\\', "/");
        let file_hash = sha256_file(path)
            .map_err(|error| format!("cannot hash JS {}: {error}", path.display()))?;
        outer.update(format!("{file_hash}  {relative}\n").as_bytes());
    }
    Ok(hex_digest(outer.finalize().as_slice()))
}

fn sha256_file(path: &Path) -> Result<String, std::io::Error> {
    let bytes = fs::read(path)?;
    Ok(hex_digest(Sha256::digest(bytes).as_slice()))
}

fn hex_digest(bytes: &[u8]) -> String {
    const HEX: &[u8; 16] = b"0123456789abcdef";
    let mut output = String::with_capacity(bytes.len() * 2);
    for &byte in bytes {
        output.push(HEX[(byte >> 4) as usize] as char);
        output.push(HEX[(byte & 0x0f) as usize] as char);
    }
    output
}

fn deno_core_version(cargo_lock: &Path) -> Result<String, String> {
    let lock = fs::read_to_string(cargo_lock)
        .map_err(|error| format!("cannot read {}: {error}", cargo_lock.display()))?;
    let mut deno_package = false;
    for line in lock.lines() {
        let line = line.trim();
        if line == "[[package]]" {
            deno_package = false;
        } else if line == "name = \"deno_core\"" {
            deno_package = true;
        } else if deno_package && line.starts_with("version = \"") {
            return line
                .strip_prefix("version = \"")
                .and_then(|value| value.strip_suffix('"'))
                .map(str::to_owned)
                .ok_or_else(|| "malformed deno_core version in Cargo.lock".to_string());
        }
    }
    Err("deno_core package missing from Cargo.lock".to_string())
}
