use std::any::Any;

use shared::protocol::audio_cmd::AudioNodeId;

use crate::param::AudioParamTimeline;

use super::AudioNodeProcessor;

/// Waveform type for OscillatorNode
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum OscillatorType {
    Sine,
    Square,
    Sawtooth,
    Triangle,
}

impl OscillatorType {
    pub fn from_str(s: &str) -> Self {
        match s {
            "square" => Self::Square,
            "sawtooth" => Self::Sawtooth,
            "triangle" => Self::Triangle,
            _ => Self::Sine,
        }
    }
}

/// Polynomial band-limited step, used to cancel the aliasing a discontinuity
/// causes.
///
/// A naive square or sawtooth is generated by evaluating an ideal, infinitely
/// sharp edge at discrete times. That edge contains energy above Nyquist, which
/// folds back down as inharmonic tones -- the buzzy, gritty quality of a
/// "digital" oscillator, worst at high frequencies where the folded partials land
/// in the middle of the spectrum. PolyBLEP subtracts a two-sample polynomial
/// approximation of the band-limited step around each discontinuity, which
/// removes most of that energy for two multiply-adds per edge.
///
/// `t` is the phase in `[0, 1)` and `dt` the phase increment per sample.
#[inline]
fn poly_blep(t: f64, dt: f64) -> f64 {
    if t < dt {
        // Just after the edge.
        let x = t / dt;
        2.0 * x - x * x - 1.0
    } else if t > 1.0 - dt {
        // Just before the next edge.
        let x = (t - 1.0) / dt;
        x * x + 2.0 * x + 1.0
    } else {
        0.0
    }
}

pub struct OscillatorNode {
    id: AudioNodeId,
    frequency: AudioParamTimeline,
    detune: AudioParamTimeline,
    osc_type: OscillatorType,
    phase: f64,
    /// Running integral of the band-limited square, which is the triangle.
    triangle: f64,
    started: bool,
    stopped: bool,
    start_when: f64,
    stop_when: f64,
}

impl OscillatorNode {
    pub fn new(id: AudioNodeId, sample_rate: u32) -> Self {
        // Nyquist for the rate actually in use. This was hardcoded to 22050,
        // which is only right at 44.1 kHz: at the 48 kHz most devices run it
        // rejected the top 2 kHz of the legal range.
        let nyquist = (sample_rate.max(2) / 2) as f32;
        Self {
            id,
            // Default frequency: 440 Hz (A4)
            frequency: AudioParamTimeline::new(440.0, -nyquist, nyquist),
            // Default detune: 0 cents
            detune: AudioParamTimeline::new(0.0, -153600.0, 153600.0),
            osc_type: OscillatorType::Sine,
            phase: 0.0,
            triangle: 0.0,
            started: false,
            stopped: false,
            start_when: 0.0,
            stop_when: f64::INFINITY,
        }
    }

    pub fn set_type(&mut self, t: OscillatorType) {
        self.osc_type = t;
    }

    pub fn start(&mut self, when: f64) {
        self.started = true;
        self.start_when = when;
    }

    pub fn stop(&mut self, when: f64) {
        self.stop_when = when;
    }

    /// Generate one band-limited sample and advance the phase.
    ///
    /// `phase_inc` is cycles per sample, so it is also the normalised distance
    /// PolyBLEP has to smooth each discontinuity over.
    #[inline]
    fn next_sample(&mut self, phase_inc: f64) -> f32 {
        let dt = phase_inc.abs().min(0.5);
        let phase = self.phase;

        let sample = match self.osc_type {
            OscillatorType::Sine => (phase * std::f64::consts::TAU).sin(),
            OscillatorType::Sawtooth => 2.0 * phase - 1.0 - poly_blep(phase, dt),
            OscillatorType::Square | OscillatorType::Triangle => {
                let naive = if phase < 0.5 { 1.0 } else { -1.0 };
                // Two edges per cycle: the rise at 0 and the fall at 0.5.
                let square =
                    naive + poly_blep(phase, dt) - poly_blep((phase + 0.5).fract(), dt);
                if self.osc_type == OscillatorType::Square {
                    square
                } else {
                    // A triangle is the integral of a square, so integrating the
                    // band-limited one gives a band-limited triangle without a
                    // second correction polynomial. The 0.999 leak drains the DC
                    // that accumulates from rounding; without it a long-running
                    // oscillator slowly walks off centre.
                    self.triangle = self.triangle * 0.999 + 4.0 * dt * square;
                    self.triangle
                }
            }
        };

        self.phase = (self.phase + phase_inc).fract();
        sample as f32
    }
}

impl AudioNodeProcessor for OscillatorNode {
    fn id(&self) -> AudioNodeId {
        self.id
    }

    fn as_any_mut(&mut self) -> &mut dyn Any {
        self
    }

    fn is_finished(&self) -> bool {
        self.stopped
    }

    fn is_producing(&self) -> bool {
        self.started && !self.stopped
    }

    fn process(
        &mut self,
        _inputs: &[f32],
        output: &mut [f32],
        sample_rate: u32,
        channels: u32,
        current_time: f64,
    ) -> usize {
        // A stop scheduled before a start is still a stop. Returning early on
        // `!started` left such a node reporting "not finished" forever, and
        // `has_active_sources` then pinned the audio thread to its 5 ms tick and
        // held the output device open for a node that would never make a sound.
        if current_time >= self.stop_when {
            self.stopped = true;
            return 0;
        }
        if !self.started || current_time < self.start_when {
            return 0;
        }

        let channels = channels.max(1) as usize;
        let frames = output.len() / channels;
        if frames == 0 {
            return 0;
        }

        let sr = sample_rate.max(1) as f64;
        let freq = self.frequency.compute_value(current_time) as f64;
        let detune = self.detune.compute_value(current_time) as f64;
        let computed_freq = freq * (2.0f64).powf(detune / 1200.0);
        let phase_inc = computed_freq / sr;

        for frame in 0..frames {
            let sample = self.next_sample(phase_inc);
            output[frame * channels..(frame + 1) * channels].fill(sample);
        }

        frames
    }

    fn get_param_mut(&mut self, name: &str) -> Option<&mut AudioParamTimeline> {
        match name {
            "frequency" => Some(&mut self.frequency),
            "detune" => Some(&mut self.detune),
            _ => None,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn render(osc_type: OscillatorType, frequency: f32, frames: usize) -> Vec<f32> {
        let mut node = OscillatorNode::new(1, 48_000);
        node.set_type(osc_type);
        node.frequency.set_value(frequency);
        node.start(0.0);
        let mut out = vec![0.0f32; frames];
        node.process(&[], &mut out, 48_000, 1, 0.0);
        out
    }

    /// Energy above Nyquist folds back as inharmonic tones. The cheapest
    /// observable proxy: a naive edge makes adjacent samples jump by the full
    /// peak-to-peak swing regardless of frequency, while a band-limited one
    /// spreads the edge over the samples the increment actually covers.
    #[test]
    fn a_high_frequency_square_edge_is_band_limited_not_instantaneous() {
        let samples = render(OscillatorType::Square, 6_000.0, 512);
        let worst = samples
            .windows(2)
            .map(|w| (w[1] - w[0]).abs())
            .fold(0.0f32, f32::max);
        assert!(
            worst < 1.95,
            "a band-limited edge must not step the full 2.0 swing in one sample, got {worst}"
        );
    }

    #[test]
    fn a_high_frequency_sawtooth_edge_is_band_limited_not_instantaneous() {
        let samples = render(OscillatorType::Sawtooth, 6_000.0, 512);
        let worst = samples
            .windows(2)
            .map(|w| (w[1] - w[0]).abs())
            .fold(0.0f32, f32::max);
        assert!(
            worst < 1.95,
            "a band-limited edge must not step the full 2.0 swing in one sample, got {worst}"
        );
    }

    /// Band-limiting must not cost the waveform its shape or level: a low
    /// frequency, where there is nothing to alias, still has to look like a
    /// sawtooth spanning roughly [-1, 1].
    #[test]
    fn a_low_frequency_sawtooth_still_spans_the_full_range() {
        let samples = render(OscillatorType::Sawtooth, 100.0, 480);
        let min = samples.iter().copied().fold(f32::MAX, f32::min);
        let max = samples.iter().copied().fold(f32::MIN, f32::max);
        assert!(min < -0.9, "sawtooth minimum was {min}");
        assert!(max > 0.9, "sawtooth maximum was {max}");
    }

    #[test]
    fn frequency_range_follows_the_context_sample_rate() {
        let node = OscillatorNode::new(1, 48_000);
        assert_eq!(node.frequency.max_value(), 24_000.0);
        let node = OscillatorNode::new(1, 44_100);
        assert_eq!(node.frequency.max_value(), 22_050.0);
    }

    /// `stop()` before `start()` used to be unobservable: the early return on
    /// `!started` meant the node never reported finishing, so it was never
    /// collected and kept the audio thread awake for the context's whole life.
    #[test]
    fn a_stop_scheduled_before_any_start_still_finishes_the_node() {
        let mut node = OscillatorNode::new(1, 48_000);
        node.stop(0.0);

        let mut out = [0.0f32; 8];
        assert_eq!(node.process(&[], &mut out, 48_000, 1, 0.0), 0);
        assert!(node.is_finished());
        assert!(!node.is_producing());
    }

    #[test]
    fn an_unstarted_oscillator_is_not_producing() {
        let node = OscillatorNode::new(1, 48_000);
        assert!(!node.is_producing());
        assert!(!node.is_finished());
    }
}
