use parking_lot::Mutex;
use std::collections::HashMap;
use std::sync::LazyLock;
use std::sync::atomic::{AtomicU32, Ordering};
use tokio::sync::oneshot;

pub type LoadResult = Result<(ImageCacheKey, u32, (usize, usize)), String>;

/// Independent counter for shared image IDs.
/// Starts from a high range to reduce collision risk with caller image IDs
/// generated by the render thread (which start from 1 and count up).
static NEXT_SHARED_ID: AtomicU32 = AtomicU32::new(0x4000_0000);

/// Allocate a unique shared image ID that is distinct from any caller
/// image ID.  Used as the key in the render thread's `shared_fv_images`.
pub fn alloc_shared_id() -> u32 {
    NEXT_SHARED_ID.fetch_add(1, Ordering::Relaxed)
}

/// Structured cache key: `(canonical_src, mount_generation)`.
///
/// Using a tuple avoids delimiter collision that string concatenation
/// would introduce (`:` is a legal path character on Linux).  An optional
/// resize suffix is encoded in `canonical_src` as `"path\0WxH"` (null byte
/// is illegal in filesystem paths so cannot collide).
pub type ImageCacheKey = (String, u64);

/// Build a cache key from a resolved path, optional resize dimensions,
/// and mount generation.
///
/// Internally the resize dimensions are folded into the path with a
/// NUL-delimited suffix (`"{src}\0{tw}x{th}"`) so the runtime-v8-side
/// alias table can key on a single `(String, u64)` per logical
/// (path, size) pair.  For boundary lookups into the decoded-RGBA
/// `migo_io::global_cache` (which uses a native `(path, gen, tw, th)` tuple),
/// use [`to_io_cache_key`] to decompose the suffix back into its
/// dimension fields.
pub fn make_cache_key(
    src: &str,
    target_width: Option<u32>,
    target_height: Option<u32>,
    mount_generation: u64,
) -> ImageCacheKey {
    let canonical = match (target_width, target_height) {
        (Some(tw), Some(th)) => format!("{}\0{}x{}", src, tw, th),
        _ => src.to_string(),
    };
    (canonical, mount_generation)
}

/// Convert a runtime-v8-side `ImageCacheKey` (mangled-suffix form) into
/// the native 4-tuple used by `migo_io::global_cache`.  Unmangled keys
/// (no NUL delimiter) map to the `(path, gen, 0, 0)` full-resolution
/// slot that [`migo_io::image_cache::full_res_key`] produces.
pub fn to_io_cache_key(key: &ImageCacheKey) -> migo_io::image_cache::ImageCacheKey {
    let (canonical, generation) = key;
    if let Some((path, dims)) = canonical.split_once('\0') {
        if let Some((tw_s, th_s)) = dims.split_once('x') {
            if let (Ok(tw), Ok(th)) = (tw_s.parse::<u32>(), th_s.parse::<u32>()) {
                return (path.to_string(), *generation, tw, th);
            }
        }
    }
    (canonical.clone(), *generation, 0, 0)
}

pub struct SharedImageEntry {
    pub shared_image_id: u32,
    pub refs: usize,
    pub dims: (usize, usize),
}

pub struct ImageCache {
    // keyed by (canonical src, mount generation)
    by_src: HashMap<ImageCacheKey, SharedImageEntry>,
    // alias (caller image_id) -> shared_image_id
    alias_to_shared: HashMap<u32, u32>,
    // shared_image_id -> cache key
    shared_to_key: HashMap<u32, ImageCacheKey>,

    // in-flight loads: key -> list of waiters
    loading_map: HashMap<ImageCacheKey, Vec<oneshot::Sender<LoadResult>>>,
    // image ids waiting on an in-flight load; used to prevent destroy-before-
    // completion from resurrecting aliases and refcounts.
    pending_alias_to_key: HashMap<u32, ImageCacheKey>,
}

pub enum BeginLoadResult {
    AlreadyLoaded((u32, (usize, usize))),
    Join(oneshot::Receiver<LoadResult>),
    StartLoading,
}

impl ImageCache {
    pub fn new() -> Self {
        Self {
            by_src: HashMap::new(),
            alias_to_shared: HashMap::new(),
            shared_to_key: HashMap::new(),
            loading_map: HashMap::new(),
            pending_alias_to_key: HashMap::new(),
        }
    }

    /// Called at start of op_load_image: remove previous alias and dec refs.
    /// Returns Some(shared_id) if refs dropped to 0 -> caller should destroy that shared_id.
    pub fn remove_previous_alias(&mut self, image_id: u32) -> Option<u32> {
        if let Some(shared_id) = self.alias_to_shared.remove(&image_id) {
            if let Some(key) = self.shared_to_key.get(&shared_id).cloned() {
                if let Some(entry) = self.by_src.get_mut(&key) {
                    entry.refs = entry.refs.saturating_sub(1);
                    // H-5: each alias removal releases exactly one
                    // pin on the io-side LRU entry.  When refs hits
                    // zero the full unpin drops the count back to
                    // regular-LRU eligibility so the bytes can age
                    // out normally; idle entries don't deserve
                    // permanent residence any more than the caller
                    // deserves a silent black texture.
                    migo_io::image_cache::global_cache().unpin(&to_io_cache_key(&key));
                    if entry.refs == 0 {
                        self.by_src.remove(&key);
                        self.shared_to_key.remove(&shared_id);
                        return Some(shared_id);
                    }
                }
            }
        }
        self.pending_alias_to_key.remove(&image_id);
        None
    }

    pub fn begin_load(&mut self, image_id: u32, key: &ImageCacheKey) -> BeginLoadResult {
        // already loaded
        if let Some(entry) = self.by_src.get_mut(key) {
            entry.refs = entry.refs.saturating_add(1);
            let shared_id = entry.shared_image_id;

            self.alias_to_shared.insert(image_id, shared_id);
            self.shared_to_key
                .entry(shared_id)
                .or_insert_with(|| key.clone());
            // H-5: every refs++ site must pair with a pin to keep
            // the live-vs-cached split consistent.  The io cache
            // side counts pins additively, so two aliases to the
            // same shared image hold two pins; releasing one
            // decrements without making the entry evictable.
            migo_io::image_cache::global_cache().pin(&to_io_cache_key(key));

            return BeginLoadResult::AlreadyLoaded((shared_id, entry.dims));
        }

        // loading in progress
        if self.loading_map.contains_key(key) {
            let (tx, rx) = oneshot::channel();
            self.loading_map.get_mut(key).unwrap().push(tx);
            self.pending_alias_to_key.insert(image_id, key.clone());
            return BeginLoadResult::Join(rx);
        }

        // become loader
        self.loading_map.insert(key.clone(), Vec::new());
        BeginLoadResult::StartLoading
    }

    /// Register the `image_id → shared_id` mapping immediately when a load
    /// starts, before the render thread responds.  This ensures
    /// `try_release_and_get_destroy_rid(image_id)` resolves to the correct
    /// `shared_id` even while the upload is still in flight.
    ///
    /// `finish_load` will overwrite with the same value (idempotent).
    pub fn register_inflight_alias(&mut self, image_id: u32, shared_id: u32) {
        self.alias_to_shared.insert(image_id, shared_id);
    }

    /// Called by *joiners* after they got (shared_id, dims), to ensure alias/ref is correct
    /// even if JS does not replace image_id.
    pub fn bind_alias_existing(
        &mut self,
        image_id: u32,
        requested_key: &ImageCacheKey,
        actual_key: &ImageCacheKey,
        shared_id: u32,
    ) {
        match self.pending_alias_to_key.get(&image_id) {
            Some(pending_key) if pending_key == requested_key => {
                self.pending_alias_to_key.remove(&image_id);
            }
            _ => return,
        }
        if let Some(entry) = self.by_src.get_mut(actual_key) {
            // entry should exist already
            entry.refs = entry.refs.saturating_add(1);
            self.alias_to_shared.insert(image_id, shared_id);
            self.shared_to_key
                .entry(shared_id)
                .or_insert_with(|| actual_key.clone());
            // H-5: joiner became a real alias; pin the io entry
            // to keep bytes alive for its texImage2D path.
            migo_io::image_cache::global_cache().pin(&to_io_cache_key(actual_key));
        }
    }

    /// Called by the loader when finished.
    ///
    /// `shared_id` is an independently allocated ID (via [`alloc_shared_id`])
    /// used as the key in the render thread's texture map.  It must NOT be
    /// the same as `loader_image_id` — reusing the caller ID would cause
    /// texture map corruption when the loader alias re-loads a different src
    /// while other aliases still reference the old shared entry.
    pub fn finish_load(
        &mut self,
        loader_image_id: u32,
        shared_id: u32,
        requested_key: &ImageCacheKey,
        actual_key: &ImageCacheKey,
        res: Result<(usize, usize), String>,
    ) -> Option<u32> {
        let Some(waiters) = self.loading_map.remove(requested_key) else {
            return None;
        };

        match res {
            Ok(dims) => {
                let loader_alive =
                    self.alias_to_shared.get(&loader_image_id).copied() == Some(shared_id);
                let pending_refs = self
                    .pending_alias_to_key
                    .values()
                    .filter(|pending| *pending == requested_key)
                    .count();
                if !loader_alive && pending_refs == 0 {
                    return Some(shared_id);
                }

                if let Some(existing) = self.by_src.get_mut(actual_key) {
                    let existing_shared_id = existing.shared_image_id;
                    if loader_alive {
                        existing.refs = existing.refs.saturating_add(1);
                        self.alias_to_shared
                            .insert(loader_image_id, existing_shared_id);
                        // H-5: loader morphed into a real alias.
                        migo_io::image_cache::global_cache().pin(&to_io_cache_key(actual_key));
                    }
                    self.shared_to_key
                        .insert(existing_shared_id, actual_key.clone());

                    for tx in waiters {
                        let _ =
                            tx.send(Ok((actual_key.clone(), existing_shared_id, existing.dims)));
                    }

                    return if existing_shared_id == shared_id {
                        None
                    } else {
                        self.shared_to_key.remove(&shared_id);
                        Some(shared_id)
                    };
                }

                self.by_src.insert(
                    actual_key.clone(),
                    SharedImageEntry {
                        shared_image_id: shared_id,
                        refs: usize::from(loader_alive),
                        dims,
                    },
                );
                if loader_alive {
                    self.alias_to_shared.insert(loader_image_id, shared_id);
                    // H-5: new shared-entry path; pin for the
                    // loader's alias.  Joiners (if any) will pin
                    // separately when their `bind_alias_existing`
                    // resolves, so each refs++ stays paired with
                    // exactly one pin.
                    migo_io::image_cache::global_cache().pin(&to_io_cache_key(actual_key));
                }
                self.shared_to_key.insert(shared_id, actual_key.clone());

                for tx in waiters {
                    let _ = tx.send(Ok((actual_key.clone(), shared_id, dims)));
                }
                None
            }
            Err(msg) => {
                if self.alias_to_shared.get(&loader_image_id).copied() == Some(shared_id) {
                    self.alias_to_shared.remove(&loader_image_id);
                }
                self.shared_to_key.remove(&shared_id);
                self.pending_alias_to_key
                    .retain(|_, pending| pending != requested_key);
                for tx in waiters {
                    let _ = tx.send(Err(msg.clone()));
                }
                None
            }
        }
    }

    /// destroy: dec refs; return Some(shared_id) if should actually destroy underlying shared resource
    pub fn try_release_and_get_destroy_rid(&mut self, image_id: u32) -> Option<u32> {
        self.pending_alias_to_key.remove(&image_id);
        let had_alias = self.alias_to_shared.contains_key(&image_id);
        let shared_id = self.alias_to_shared.remove(&image_id).unwrap_or(image_id);

        if let Some(key) = self.shared_to_key.get(&shared_id).cloned() {
            if let Some(entry) = self.by_src.get_mut(&key) {
                if entry.refs > 0 {
                    entry.refs -= 1;
                    // H-5: one alias released → unpin once.  When
                    // entry.refs still > 0 the remaining aliases
                    // keep their own pins, so the io entry
                    // stays live.  When refs hits zero the
                    // final unpin here transitions the entry
                    // to LRU-evictable.
                    migo_io::image_cache::global_cache().unpin(&to_io_cache_key(&key));
                }
                if entry.refs == 0 {
                    self.by_src.remove(&key);
                    self.shared_to_key.remove(&shared_id);
                    return Some(shared_id);
                }
                return None;
            }
        }

        if had_alias {
            Some(shared_id)
        } else {
            // not tracked as shared -> destroy caller id directly
            Some(image_id)
        }
    }

    /// Get the source path for an image ID (for texImage2D RGBA lookup).
    #[allow(dead_code)]
    pub fn source_for_image_id(&self, image_id: u32) -> Option<String> {
        let shared_id = self
            .alias_to_shared
            .get(&image_id)
            .copied()
            .unwrap_or(image_id);
        self.shared_to_key
            .get(&shared_id)
            .map(|(path, _)| path.clone())
    }

    /// Get the full cache key `(path, generation)` for an image ID.
    pub fn cache_key_for_image_id(&self, image_id: u32) -> Option<ImageCacheKey> {
        let shared_id = self
            .alias_to_shared
            .get(&image_id)
            .copied()
            .unwrap_or(image_id);
        self.shared_to_key.get(&shared_id).cloned()
    }

    /// Resolve a caller-side `image_id` (alias) to the underlying
    /// shared image identifier and its decoded dimensions, if known.
    ///
    /// Returns `None` if no alias has been registered yet (e.g. the
    /// caller invented an `image_id` it never loaded) or if the
    /// underlying load is still in flight.  The dimensions are taken
    /// from the cache entry so callers don't need to round-trip to
    /// the render thread to learn texture extents.
    pub fn shared_for_image_id(&self, image_id: u32) -> Option<(u32, (usize, usize))> {
        let shared_id = self.alias_to_shared.get(&image_id).copied()?;
        let key = self.shared_to_key.get(&shared_id)?;
        let entry = self.by_src.get(key)?;
        Some((shared_id, entry.dims))
    }
}

pub static IMAGE_CACHE: LazyLock<Mutex<ImageCache>> =
    LazyLock::new(|| Mutex::new(ImageCache::new()));

/// Clear all shared image tracking state.
///
/// Must be called during host shutdown to prevent stale entries from
/// leaking into the next session (IMAGE_CACHE is process-global).
pub fn drain_shared_image_cache() -> Vec<u32> {
    use std::collections::HashSet;
    let mut c = IMAGE_CACHE.lock();
    let mut seen = HashSet::new();
    let mut shared_ids: Vec<u32> = Vec::new();
    for id in c
        .by_src
        .values()
        .map(|e| e.shared_image_id)
        .chain(c.alias_to_shared.values().copied())
    {
        if seen.insert(id) {
            shared_ids.push(id);
        }
    }
    // H-5: release every pin we ever took before wiping the
    // tracking maps.  Each (key, entry) pair held one pin per
    // `refs` unit; draining must undo them all so the io cache
    // doesn't carry dead pins into the next session (which
    // would make those entries permanently un-evictable even
    // after their aliases are gone).
    let pin_releases: Vec<(migo_io::image_cache::ImageCacheKey, usize)> = c
        .by_src
        .iter()
        .map(|(k, v)| (to_io_cache_key(k), v.refs))
        .collect();
    {
        let mut io_cache = migo_io::image_cache::global_cache();
        for (io_key, refs) in pin_releases {
            for _ in 0..refs {
                io_cache.unpin(&io_key);
            }
        }
    }
    c.by_src.clear();
    c.alias_to_shared.clear();
    c.shared_to_key.clear();
    c.loading_map.clear();
    c.pending_alias_to_key.clear();
    shared_ids
}

pub fn clear_shared_image_cache() {
    let _ = drain_shared_image_cache();
}

#[cfg(test)]
mod tests {
    use super::{ImageCache, ImageCacheKey};

    #[test]
    fn finish_load_merges_converging_actual_keys_without_losing_refs() {
        let mut cache = ImageCache::new();
        let requested_a: ImageCacheKey = ("/code/a.png".into(), 10);
        let requested_b: ImageCacheKey = ("/code/b.png".into(), 11);
        let actual: ImageCacheKey = ("/code/shared.png".into(), 20);

        assert!(matches!(
            cache.begin_load(1, &requested_a),
            super::BeginLoadResult::StartLoading
        ));
        assert!(matches!(
            cache.begin_load(2, &requested_b),
            super::BeginLoadResult::StartLoading
        ));
        cache.register_inflight_alias(1, 100);
        cache.register_inflight_alias(2, 200);

        assert_eq!(
            cache.finish_load(1, 100, &requested_a, &actual, Ok((64, 64))),
            None
        );
        assert_eq!(
            cache.finish_load(2, 200, &requested_b, &actual, Ok((64, 64))),
            Some(200)
        );

        let entry = cache
            .by_src
            .get(&actual)
            .expect("merged entry should exist");
        assert_eq!(entry.shared_image_id, 100);
        assert_eq!(entry.refs, 2);
        assert_eq!(cache.alias_to_shared.get(&1), Some(&100));
        assert_eq!(cache.alias_to_shared.get(&2), Some(&100));
        assert_eq!(cache.shared_to_key.get(&100), Some(&actual));
        assert!(!cache.shared_to_key.contains_key(&200));
    }

    #[test]
    fn bind_alias_existing_ignores_stale_waiters_for_replaced_loads() {
        let mut cache = ImageCache::new();
        let requested_a: ImageCacheKey = ("/code/a.png".into(), 10);
        let requested_b: ImageCacheKey = ("/code/b.png".into(), 11);
        let actual_a: ImageCacheKey = ("/code/a.png".into(), 20);

        cache.begin_load(7, &requested_a);
        let _ = cache.begin_load(7, &requested_b);
        cache.pending_alias_to_key.insert(7, requested_b.clone());
        cache.by_src.insert(
            actual_a.clone(),
            super::SharedImageEntry {
                shared_image_id: 100,
                refs: 1,
                dims: (32, 32),
            },
        );

        cache.bind_alias_existing(7, &requested_a, &actual_a, 100);

        assert_eq!(cache.alias_to_shared.get(&7), None);
        assert_eq!(cache.pending_alias_to_key.get(&7), Some(&requested_b));
        assert_eq!(cache.by_src.get(&actual_a).unwrap().refs, 1);
    }

    #[test]
    fn finish_load_error_clears_loader_and_waiter_bookkeeping() {
        let mut cache = ImageCache::new();
        let requested: ImageCacheKey = ("/code/a.png".into(), 10);

        assert!(matches!(
            cache.begin_load(1, &requested),
            super::BeginLoadResult::StartLoading
        ));
        let _ = cache.begin_load(2, &requested);
        cache.register_inflight_alias(1, 100);

        assert_eq!(
            cache.finish_load(1, 100, &requested, &requested, Err("boom".into())),
            None
        );

        assert!(!cache.alias_to_shared.contains_key(&1));
        assert!(!cache.pending_alias_to_key.contains_key(&2));
        assert!(!cache.loading_map.contains_key(&requested));
    }
}
