[package]
name = "platform"
version = "0.1.0"
edition = "2024"

[lib]
name = "platform"
path = "lib.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
lazy_static = "1.5.0"
core = {path = "../core"}
shared = {path = "../shared"}
js-runtime = {path = "../js-runtime"}
graphics = {path = "../graphics"}
io = {path = "../io"}
crossbeam-channel = { workspace = true }
futures = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
deno_error = { workspace = true }
deno_core = { workspace = true }
raw-window-handle = { workspace = true }

[target.'cfg(target_os = "android")'.dependencies]
jni = "0.21"
ndk-context = "0.1"
tracing-android = { workspace = true }
