use parking_lot::Mutex;
use std::collections::HashMap;
use std::sync::atomic::{AtomicU32, Ordering};
use std::sync::LazyLock;
use tokio::sync::oneshot;

/// Independent counter for shared image IDs.
/// Starts from a high range to reduce collision risk with caller image IDs
/// generated by the render thread (which start from 1 and count up).
static NEXT_SHARED_ID: AtomicU32 = AtomicU32::new(0x4000_0000);

/// Allocate a unique shared image ID that is distinct from any caller
/// image ID.  Used as the key in the render thread's `shared_fv_images`.
pub fn alloc_shared_id() -> u32 {
    NEXT_SHARED_ID.fetch_add(1, Ordering::Relaxed)
}

pub struct SharedImageEntry {
    pub shared_image_id: u32,
    pub refs: usize,
    pub dims: (usize, usize),
}

pub struct ImageCache {
    // keyed by canonical src
    by_src: HashMap<String, SharedImageEntry>,
    // alias (caller image_id) -> shared_image_id
    alias_to_shared: HashMap<u32, u32>,
    // shared_image_id -> src
    shared_to_src: HashMap<u32, String>,

    // in-flight loads: src -> list of waiters
    loading_map: HashMap<String, Vec<oneshot::Sender<Result<(u32, (usize, usize)), String>>>>,
}

pub enum BeginLoadResult {
    AlreadyLoaded((u32, (usize, usize))),
    Join(oneshot::Receiver<Result<(u32, (usize, usize)), String>>),
    StartLoading,
}

impl ImageCache {
    pub fn new() -> Self {
        Self {
            by_src: HashMap::new(),
            alias_to_shared: HashMap::new(),
            shared_to_src: HashMap::new(),
            loading_map: HashMap::new(),
        }
    }

    /// Called at start of op_load_image: remove previous alias and dec refs.
    /// Returns Some(shared_id) if refs dropped to 0 -> caller should destroy that shared_id.
    pub fn remove_previous_alias(&mut self, image_id: u32) -> Option<u32> {
        if let Some(shared_id) = self.alias_to_shared.remove(&image_id) {
            if let Some(src) = self.shared_to_src.get(&shared_id).cloned() {
                if let Some(entry) = self.by_src.get_mut(&src) {
                    entry.refs = entry.refs.saturating_sub(1);
                    if entry.refs == 0 {
                        self.by_src.remove(&src);
                        self.shared_to_src.remove(&shared_id);
                        return Some(shared_id);
                    }
                }
            }
        }
        None
    }

    pub fn begin_load(&mut self, image_id: u32, src: &str) -> BeginLoadResult {
        // already loaded
        if let Some(entry) = self.by_src.get_mut(src) {
            entry.refs = entry.refs.saturating_add(1);
            let shared_id = entry.shared_image_id;

            self.alias_to_shared.insert(image_id, shared_id);
            self.shared_to_src
                .entry(shared_id)
                .or_insert_with(|| src.to_string());

            return BeginLoadResult::AlreadyLoaded((shared_id, entry.dims));
        }

        // loading in progress
        if self.loading_map.contains_key(src) {
            let (tx, rx) = oneshot::channel();
            self.loading_map.get_mut(src).unwrap().push(tx);
            return BeginLoadResult::Join(rx);
        }

        // become loader
        self.loading_map.insert(src.to_string(), Vec::new());
        BeginLoadResult::StartLoading
    }

    /// Register the `image_id → shared_id` mapping immediately when a load
    /// starts, before the render thread responds.  This ensures
    /// `try_release_and_get_destroy_rid(image_id)` resolves to the correct
    /// `shared_id` even while the upload is still in flight.
    ///
    /// `finish_load` will overwrite with the same value (idempotent).
    pub fn register_inflight_alias(&mut self, image_id: u32, shared_id: u32) {
        self.alias_to_shared.insert(image_id, shared_id);
    }

    /// Called by *joiners* after they got (shared_id, dims), to ensure alias/ref is correct
    /// even if JS does not replace image_id.
    pub fn bind_alias_existing(&mut self, image_id: u32, src: &str, shared_id: u32) {
        if let Some(entry) = self.by_src.get_mut(src) {
            // entry should exist already
            entry.refs = entry.refs.saturating_add(1);
            self.alias_to_shared.insert(image_id, shared_id);
            self.shared_to_src
                .entry(shared_id)
                .or_insert_with(|| src.to_string());
        }
    }

    /// Called by the loader when finished.
    ///
    /// `shared_id` is an independently allocated ID (via [`alloc_shared_id`])
    /// used as the key in the render thread's texture map.  It must NOT be
    /// the same as `loader_image_id` — reusing the caller ID would cause
    /// texture map corruption when the loader alias re-loads a different src
    /// while other aliases still reference the old shared entry.
    pub fn finish_load(
        &mut self,
        loader_image_id: u32,
        shared_id: u32,
        src: &str,
        res: Result<(usize, usize), String>,
    ) {
        let waiters = self.loading_map.remove(src).unwrap_or_default();

        match res {
            Ok(dims) => {
                self.by_src.insert(
                    src.to_string(),
                    SharedImageEntry {
                        shared_image_id: shared_id,
                        refs: 1,
                        dims,
                    },
                );
                self.alias_to_shared.insert(loader_image_id, shared_id);
                self.shared_to_src.insert(shared_id, src.to_string());

                for tx in waiters {
                    let _ = tx.send(Ok((shared_id, dims)));
                }
            }
            Err(msg) => {
                for tx in waiters {
                    let _ = tx.send(Err(msg.clone()));
                }
            }
        }
    }

    /// destroy: dec refs; return Some(shared_id) if should actually destroy underlying shared resource
    pub fn try_release_and_get_destroy_rid(&mut self, image_id: u32) -> Option<u32> {
        let shared_id = self.alias_to_shared.remove(&image_id).unwrap_or(image_id);

        if let Some(src) = self.shared_to_src.get(&shared_id).cloned() {
            if let Some(entry) = self.by_src.get_mut(&src) {
                if entry.refs > 0 {
                    entry.refs -= 1;
                }
                if entry.refs == 0 {
                    self.by_src.remove(&src);
                    self.shared_to_src.remove(&shared_id);
                    return Some(shared_id);
                }
                return None;
            }
        }

        // not tracked as shared -> destroy caller id directly
        Some(image_id)
    }

    pub fn source_for_image_id(&self, image_id: u32) -> Option<String> {
        let shared_id = self
            .alias_to_shared
            .get(&image_id)
            .copied()
            .unwrap_or(image_id);
        self.shared_to_src.get(&shared_id).cloned()
    }
}

pub static IMAGE_CACHE: LazyLock<Mutex<ImageCache>> =
    LazyLock::new(|| Mutex::new(ImageCache::new()));

/// Clear all shared image tracking state.
///
/// Must be called during host shutdown to prevent stale entries from
/// leaking into the next session (IMAGE_CACHE is process-global).
pub fn clear_shared_image_cache() {
    NEXT_SHARED_ID.store(0x4000_0000, Ordering::Relaxed);
    let mut c = IMAGE_CACHE.lock();
    c.by_src.clear();
    c.alias_to_shared.clear();
    c.shared_to_src.clear();
    c.loading_map.clear();
}
