use parking_lot::Mutex;
use std::collections::HashMap;
use std::sync::atomic::{AtomicU32, Ordering};
use std::sync::LazyLock;
use tokio::sync::oneshot;

/// Independent counter for shared image IDs.
/// Starts from a high range to reduce collision risk with caller image IDs
/// generated by the render thread (which start from 1 and count up).
static NEXT_SHARED_ID: AtomicU32 = AtomicU32::new(0x4000_0000);

/// Allocate a unique shared image ID that is distinct from any caller
/// image ID.  Used as the key in the render thread's `shared_fv_images`.
pub fn alloc_shared_id() -> u32 {
    NEXT_SHARED_ID.fetch_add(1, Ordering::Relaxed)
}

/// Structured cache key: `(canonical_src, mount_generation)`.
///
/// Using a tuple avoids delimiter collision that string concatenation
/// would introduce (`:` is a legal path character on Linux).  An optional
/// resize suffix is encoded in `canonical_src` as `"path\0WxH"` (null byte
/// is illegal in filesystem paths so cannot collide).
pub type ImageCacheKey = (String, u64);

/// Build a cache key from a resolved path, optional resize dimensions,
/// and mount generation.
pub fn make_cache_key(
    src: &str,
    target_width: Option<u32>,
    target_height: Option<u32>,
    mount_generation: u64,
) -> ImageCacheKey {
    let canonical = match (target_width, target_height) {
        (Some(tw), Some(th)) => format!("{}\0{}x{}", src, tw, th),
        _ => src.to_string(),
    };
    (canonical, mount_generation)
}

pub struct SharedImageEntry {
    pub shared_image_id: u32,
    pub refs: usize,
    pub dims: (usize, usize),
}

pub struct ImageCache {
    // keyed by (canonical src, mount generation)
    by_src: HashMap<ImageCacheKey, SharedImageEntry>,
    // alias (caller image_id) -> shared_image_id
    alias_to_shared: HashMap<u32, u32>,
    // shared_image_id -> cache key
    shared_to_key: HashMap<u32, ImageCacheKey>,

    // in-flight loads: key -> list of waiters
    loading_map:
        HashMap<ImageCacheKey, Vec<oneshot::Sender<Result<(u32, (usize, usize)), String>>>>,
    // image ids waiting on an in-flight load; used to prevent destroy-before-
    // completion from resurrecting aliases and refcounts.
    pending_alias_to_key: HashMap<u32, ImageCacheKey>,
}

pub enum BeginLoadResult {
    AlreadyLoaded((u32, (usize, usize))),
    Join(oneshot::Receiver<Result<(u32, (usize, usize)), String>>),
    StartLoading,
}

impl ImageCache {
    pub fn new() -> Self {
        Self {
            by_src: HashMap::new(),
            alias_to_shared: HashMap::new(),
            shared_to_key: HashMap::new(),
            loading_map: HashMap::new(),
            pending_alias_to_key: HashMap::new(),
        }
    }

    /// Called at start of op_load_image: remove previous alias and dec refs.
    /// Returns Some(shared_id) if refs dropped to 0 -> caller should destroy that shared_id.
    pub fn remove_previous_alias(&mut self, image_id: u32) -> Option<u32> {
        if let Some(shared_id) = self.alias_to_shared.remove(&image_id) {
            if let Some(key) = self.shared_to_key.get(&shared_id).cloned() {
                if let Some(entry) = self.by_src.get_mut(&key) {
                    entry.refs = entry.refs.saturating_sub(1);
                    if entry.refs == 0 {
                        self.by_src.remove(&key);
                        self.shared_to_key.remove(&shared_id);
                        return Some(shared_id);
                    }
                }
            }
        }
        self.pending_alias_to_key.remove(&image_id);
        None
    }

    pub fn begin_load(&mut self, image_id: u32, key: &ImageCacheKey) -> BeginLoadResult {
        // already loaded
        if let Some(entry) = self.by_src.get_mut(key) {
            entry.refs = entry.refs.saturating_add(1);
            let shared_id = entry.shared_image_id;

            self.alias_to_shared.insert(image_id, shared_id);
            self.shared_to_key
                .entry(shared_id)
                .or_insert_with(|| key.clone());

            return BeginLoadResult::AlreadyLoaded((shared_id, entry.dims));
        }

        // loading in progress
        if self.loading_map.contains_key(key) {
            let (tx, rx) = oneshot::channel();
            self.loading_map.get_mut(key).unwrap().push(tx);
            self.pending_alias_to_key.insert(image_id, key.clone());
            return BeginLoadResult::Join(rx);
        }

        // become loader
        self.loading_map.insert(key.clone(), Vec::new());
        BeginLoadResult::StartLoading
    }

    /// Register the `image_id → shared_id` mapping immediately when a load
    /// starts, before the render thread responds.  This ensures
    /// `try_release_and_get_destroy_rid(image_id)` resolves to the correct
    /// `shared_id` even while the upload is still in flight.
    ///
    /// `finish_load` will overwrite with the same value (idempotent).
    pub fn register_inflight_alias(&mut self, image_id: u32, shared_id: u32) {
        self.alias_to_shared.insert(image_id, shared_id);
    }

    /// Called by *joiners* after they got (shared_id, dims), to ensure alias/ref is correct
    /// even if JS does not replace image_id.
    pub fn bind_alias_existing(&mut self, image_id: u32, key: &ImageCacheKey, shared_id: u32) {
        match self.pending_alias_to_key.remove(&image_id) {
            Some(pending_key) if &pending_key == key => {}
            _ => return,
        }
        if let Some(entry) = self.by_src.get_mut(key) {
            // entry should exist already
            entry.refs = entry.refs.saturating_add(1);
            self.alias_to_shared.insert(image_id, shared_id);
            self.shared_to_key
                .entry(shared_id)
                .or_insert_with(|| key.clone());
        }
    }

    /// Called by the loader when finished.
    ///
    /// `shared_id` is an independently allocated ID (via [`alloc_shared_id`])
    /// used as the key in the render thread's texture map.  It must NOT be
    /// the same as `loader_image_id` — reusing the caller ID would cause
    /// texture map corruption when the loader alias re-loads a different src
    /// while other aliases still reference the old shared entry.
    pub fn finish_load(
        &mut self,
        loader_image_id: u32,
        shared_id: u32,
        key: &ImageCacheKey,
        res: Result<(usize, usize), String>,
    ) -> Option<u32> {
        let Some(waiters) = self.loading_map.remove(key) else {
            return None;
        };

        match res {
            Ok(dims) => {
                let loader_alive =
                    self.alias_to_shared.get(&loader_image_id).copied() == Some(shared_id);
                let pending_refs = self
                    .pending_alias_to_key
                    .values()
                    .filter(|pending| *pending == key)
                    .count();
                if !loader_alive && pending_refs == 0 {
                    return Some(shared_id);
                }
                self.by_src.insert(
                    key.clone(),
                    SharedImageEntry {
                        shared_image_id: shared_id,
                        refs: usize::from(loader_alive),
                        dims,
                    },
                );
                if loader_alive {
                    self.alias_to_shared.insert(loader_image_id, shared_id);
                }
                self.shared_to_key.insert(shared_id, key.clone());

                for tx in waiters {
                    let _ = tx.send(Ok((shared_id, dims)));
                }
                None
            }
            Err(msg) => {
                for tx in waiters {
                    let _ = tx.send(Err(msg.clone()));
                }
                None
            }
        }
    }

    /// destroy: dec refs; return Some(shared_id) if should actually destroy underlying shared resource
    pub fn try_release_and_get_destroy_rid(&mut self, image_id: u32) -> Option<u32> {
        self.pending_alias_to_key.remove(&image_id);
        let had_alias = self.alias_to_shared.contains_key(&image_id);
        let shared_id = self.alias_to_shared.remove(&image_id).unwrap_or(image_id);

        if let Some(key) = self.shared_to_key.get(&shared_id).cloned() {
            if let Some(entry) = self.by_src.get_mut(&key) {
                if entry.refs > 0 {
                    entry.refs -= 1;
                }
                if entry.refs == 0 {
                    self.by_src.remove(&key);
                    self.shared_to_key.remove(&shared_id);
                    return Some(shared_id);
                }
                return None;
            }
        }

        if had_alias {
            Some(shared_id)
        } else {
            // not tracked as shared -> destroy caller id directly
            Some(image_id)
        }
    }

    /// Get the source path for an image ID (for texImage2D RGBA lookup).
    #[allow(dead_code)]
    pub fn source_for_image_id(&self, image_id: u32) -> Option<String> {
        let shared_id = self
            .alias_to_shared
            .get(&image_id)
            .copied()
            .unwrap_or(image_id);
        self.shared_to_key
            .get(&shared_id)
            .map(|(path, _)| path.clone())
    }

    /// Get the full cache key `(path, generation)` for an image ID.
    pub fn cache_key_for_image_id(&self, image_id: u32) -> Option<ImageCacheKey> {
        let shared_id = self
            .alias_to_shared
            .get(&image_id)
            .copied()
            .unwrap_or(image_id);
        self.shared_to_key.get(&shared_id).cloned()
    }
}

pub static IMAGE_CACHE: LazyLock<Mutex<ImageCache>> =
    LazyLock::new(|| Mutex::new(ImageCache::new()));

/// Clear all shared image tracking state.
///
/// Must be called during host shutdown to prevent stale entries from
/// leaking into the next session (IMAGE_CACHE is process-global).
pub fn drain_shared_image_cache() -> Vec<u32> {
    use std::collections::HashSet;
    let mut c = IMAGE_CACHE.lock();
    let mut seen = HashSet::new();
    let mut shared_ids: Vec<u32> = Vec::new();
    for id in c.by_src.values().map(|e| e.shared_image_id).chain(c.alias_to_shared.values().copied()) {
        if seen.insert(id) {
            shared_ids.push(id);
        }
    }
    c.by_src.clear();
    c.alias_to_shared.clear();
    c.shared_to_key.clear();
    c.loading_map.clear();
    c.pending_alias_to_key.clear();
    shared_ids
}

pub fn clear_shared_image_cache() {
    let _ = drain_shared_image_cache();
}
