#!/usr/bin/env python3
"""Generate the Android C ABI package's CMake integration and artifact manifest.

The Android package is cross-compiled and ships a static library the host links
into its own `.so`. Like the Linux generator, the consumer's link line is
derived from cargo's own `--print native-static-libs` rather than maintained by
hand, so it cannot drift from the build.

Every field the manifest records is checked against reality by
scripts/test-android-sdk-contract.sh; the manifest is a claim the gate verifies,
not documentation that drifts.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import pathlib
import re
import sys

_NOTE_RE = re.compile(r"native-static-libs:\s*(?P<libs>.+)")
_PACKAGE_VERSION_RE = re.compile(
    r"^(?:0|[1-9][0-9]*)\."
    r"(?:0|[1-9][0-9]*)\."
    r"(?:0|[1-9][0-9]*)"
    r"(?:-(?:0|[1-9][0-9]*|[0-9A-Za-z-]*[A-Za-z-][0-9A-Za-z-]*)"
    r"(?:\.(?:0|[1-9][0-9]*|[0-9A-Za-z-]*[A-Za-z-][0-9A-Za-z-]*))*)?"
    r"(?:\+[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*)?$"
)

# arch -> (android_abi, triple, cpu_baseline, required_cpu_features)
ARCH = {
    "aarch64": ("arm64-v8a", "aarch64-linux-android", "armv8-a", ["neon"]),
    "x86_64": ("x86_64", "x86_64-linux-android", "x86-64-v1", ["cmov", "sse2"]),
}
ANDROID_API_FLOOR = "26"


def package_version(value: str) -> str:
    """Return a safe SemVer used in generated CMake and manifest content."""
    try:
        encoded = value.encode("ascii")
    except UnicodeEncodeError as error:
        raise ValueError("package version must be ASCII SemVer") from error
    if len(encoded) > 128 or _PACKAGE_VERSION_RE.fullmatch(value) is None:
        raise ValueError(f"package version is not valid SemVer: {value!r}")
    return value


# The NDK clang driver links these automatically for a shared library or
# executable, and the C++ runtime it links is the consumer's own -DANDROID_STL
# choice. Recording them would over-link -- and listing both c++_static and
# c++_shared, as cargo's transitive note does, is contradictory: a consumer
# links exactly one STL. What the package records is only what a consumer must
# add on top of the toolchain: the platform libraries the archive references.
ANDROID_IMPLICIT_LIBS = {
    "c", "m", "dl", "unwind", "gcc", "gcc_eh",
    "c++_shared", "c++_static", "c++abi",
}


def parse_native_static_libs(text: str) -> list[str]:
    match = _NOTE_RE.search(text)
    if not match:
        raise ValueError("no 'native-static-libs:' note found in cargo output")
    seen: set[str] = set()
    libs: list[str] = []
    for token in match["libs"].split():
        # Only -l flags describe libraries the consumer must provide; drop the
        # absolute object paths cargo also lists for its own linking.
        if not token.startswith("-l"):
            continue
        name = token[2:]
        if name in ANDROID_IMPLICIT_LIBS:
            continue
        if token not in seen:
            seen.add(token)
            libs.append(token)
    if not libs:
        raise ValueError("no consumer-facing link libraries after filtering the toolchain set")
    return sorted(libs)


def sha256_file(path: pathlib.Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


def artifact_identity(prefix: pathlib.Path, path: pathlib.Path) -> tuple[str, dict]:
    if path.is_symlink() or not path.is_file():
        raise ValueError(f"package artifact must be a regular file: {path}")
    try:
        relative = path.relative_to(prefix).as_posix()
    except ValueError as error:
        raise ValueError(f"artifact is outside package prefix: {path}") from error
    return relative, {
        "size_bytes": path.stat().st_size,
        "sha256": sha256_file(path),
    }


def package_artifacts(
    prefix: pathlib.Path, *, exclude: set[str] | None = None
) -> dict[str, dict]:
    """Hash the complete staged regular-file set, excluding the manifest itself."""
    excluded = exclude or set()
    artifacts: dict[str, dict] = {}
    paths = sorted(
        prefix.rglob("*"),
        key=lambda path: path.relative_to(prefix).as_posix().encode("utf-8"),
    )
    for path in paths:
        if path.is_symlink() or not path.is_file():
            continue
        relative, identity = artifact_identity(prefix, path)
        if relative not in excluded:
            artifacts[relative] = identity
    return artifacts


def render_cmake_config(version: str, libs: list[str]) -> str:
    version = package_version(version)
    interface_libs = ";".join(lib[2:] for lib in libs if lib.startswith("-l"))
    return f"""\
# Generated by scripts/gen-android-package-metadata.py -- do not edit.
#
# Consume with the NDK toolchain:
#   cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake \\
#         -DANDROID_ABI=arm64-v8a -DANDROID_PLATFORM=android-{ANDROID_API_FLOOR} \\
#         -DCMAKE_PREFIX_PATH=<this package prefix> ...
cmake_minimum_required(VERSION 3.16)

get_filename_component(MIGO_PREFIX "${{CMAKE_CURRENT_LIST_DIR}}/../../.." ABSOLUTE)

set(MIGO_VERSION "{version}")
set(MIGO_INCLUDE_DIRS "${{MIGO_PREFIX}}/include")
set(MIGO_LIBRARY "${{MIGO_PREFIX}}/lib/libmigo_capi.a")

add_library(migo::migo STATIC IMPORTED)
set_target_properties(migo::migo PROPERTIES
    IMPORTED_LOCATION "${{MIGO_LIBRARY}}"
    INTERFACE_INCLUDE_DIRECTORIES "${{MIGO_INCLUDE_DIRS}}"
    INTERFACE_LINK_LIBRARIES "{interface_libs}")

set(migo_FOUND TRUE)
"""


def render_cmake_version(version: str) -> str:
    version = package_version(version)
    return f"""\
# Generated by scripts/gen-android-package-metadata.py -- do not edit.
set(PACKAGE_VERSION "{version}")
if(PACKAGE_VERSION VERSION_LESS PACKAGE_FIND_VERSION)
    set(PACKAGE_VERSION_COMPATIBLE FALSE)
else()
    set(PACKAGE_VERSION_COMPATIBLE TRUE)
    if(PACKAGE_VERSION VERSION_EQUAL PACKAGE_FIND_VERSION)
        set(PACKAGE_VERSION_EXACT TRUE)
    endif()
endif()
"""


def render_manifest(
    *, version, arch, libs, snapshot, v8, build_metadata, artifacts
) -> dict:
    version = package_version(version)
    android_abi, triple, cpu_baseline, features = ARCH[arch]
    return {
        "schema": "migo-android-package-manifest/v2",
        "version": version,
        "product_profile": "full",
        "build_type": "release",
        "codegen_profile": "z",
        "os": "android",
        # Bionic userspace, not the Linux kernel it shares with glibc/OpenHarmony.
        "abi": "android",
        "arch": arch,
        "android_abi": android_abi,
        "target_triple": triple,
        "cpu_baseline": cpu_baseline,
        "required_cpu_features": sorted(features),
        "min_android_api": ANDROID_API_FLOOR,
        "link_libraries": libs,
        # Android always embeds a snapshot -- the runtime-v8 build embeds one per
        # ABI. "none" is a Linux-only policy.
        "snapshot_policy": "embedded",
        "snapshots": [snapshot],
        "v8": v8,
        "toolchain": build_metadata["toolchain"],
        "graphics": {
            "backend_family": "gles-native",
            "required_api": "OpenGL ES 3.0",
        },
        "provenance": build_metadata["provenance"],
        "artifacts": artifacts,
    }


def read_build_metadata(path: pathlib.Path) -> dict:
    data = json.loads(path.read_text(encoding="utf-8"))
    if data.get("schema") != "migo-android-build-metadata/v1":
        raise ValueError(f"unsupported Android build metadata schema: {path}")
    if set(data) != {"schema", "toolchain", "provenance"}:
        raise ValueError(f"Android build metadata has unexpected fields: {path}")
    provenance = data.get("provenance")
    if not isinstance(provenance, dict):
        raise ValueError(f"Android build metadata provenance is not an object: {path}")
    if provenance.get("build_recipe") != "scripts/build-android-sdk.sh":
        raise ValueError("Android C SDK build metadata names the wrong build recipe")
    recipe = pathlib.Path(__file__).resolve().parent / "build-android-sdk.sh"
    if provenance.get("build_recipe_sha256") != sha256_file(recipe):
        raise ValueError("Android C SDK build recipe hash does not match the repository")
    licenses = provenance.get("licenses")
    if not isinstance(licenses, list) or "BSL-1.1" not in licenses:
        raise ValueError("Android C SDK metadata must record the current BSL-1.1 license")
    return {"toolchain": data["toolchain"], "provenance": provenance}


def snapshot_identity(
    snapshot_bin: pathlib.Path,
    snapshot_manifest: pathlib.Path,
    arch: str,
) -> dict:
    _, triple, _, _ = ARCH[arch]
    data = json.loads(snapshot_manifest.read_text())
    if data.get("arch") != arch or data.get("target_triple") != triple:
        raise ValueError(
            f"snapshot manifest target {data.get('target_triple')}/{data.get('arch')} "
            f"does not match package target {triple}/{arch}"
        )
    actual_size = snapshot_bin.stat().st_size
    if data.get("snapshot_size") != actual_size:
        raise ValueError(
            f"snapshot_size mismatch: manifest={data.get('snapshot_size')}, file={actual_size}"
        )
    actual_hash = sha256_file(snapshot_bin)
    if data.get("snapshot_sha256") != actual_hash:
        raise ValueError(
            f"snapshot_sha256 mismatch: manifest={data.get('snapshot_sha256')}, file={actual_hash}"
        )
    return {
        "runtime_kind": data["snapshot_kind"],
        "product_profile": data["profile"],
        "target_triple": data["target_triple"],
        "arch": data["arch"],
        "schema": str(data["schema_version"]),
        "generator": "migo-snapshot-gen/0.1.0",
        "generation_cpu_policy": data["generation_cpu_policy"],
        "normalized_parameters": data["normalized_parameters"],
        "external_references_hash": data["external_references_sha256"],
        "bootstrap_inputs_hash": data["bootstrap_inputs_sha256"],
        "features": data["features"],
        "features_hash": data["features_sha256"],
        "rust_sources_hash": data["rust_sources_sha256"],
        "v8_archive_hash": data["v8_archive_sha256"],
        "bytes_size": data["snapshot_size"],
        "bytes_hash": data["snapshot_sha256"],
        "js_sources_hash": data["js_sources_sha256"],
        "deno_core_version": data["deno_core_version"],
    }


def v8_identity(component_manifest: pathlib.Path, arch: str) -> dict:
    data = json.loads(component_manifest.read_text())
    _, triple, _, _ = ARCH[arch]
    if data.get("schema") != "migo-v8-component-manifest/v1":
        raise ValueError(f"unsupported V8 component manifest schema: {component_manifest}")
    target = data.get("target")
    if not isinstance(target, dict) or target.get("triple") != triple:
        raise ValueError(
            f"V8 component target does not match package target {triple}: {component_manifest}"
        )
    return data


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--prefix", required=True, help="staged package prefix")
    parser.add_argument("--version", required=True)
    parser.add_argument("--arch", required=True, choices=sorted(ARCH))
    parser.add_argument("--cargo-output",
                        help="file holding the cargo --print native-static-libs output")
    parser.add_argument("--manifest", action="store_true",
                        help="write the artifact manifest instead of the CMake metadata")
    parser.add_argument("--snapshot-bin", help="embedded snapshot .bin (for --manifest)")
    parser.add_argument("--snapshot-manifest",
                        help="verified snapshot manifest (for --manifest)")
    parser.add_argument("--v8-component-manifest",
                        help="verified V8 component manifest (for --manifest)")
    parser.add_argument("--build-metadata",
                        help="verified Android runtime build metadata (for --manifest)")
    args = parser.parse_args()

    prefix = pathlib.Path(args.prefix)
    android_abi = ARCH[args.arch][0]

    if not args.cargo_output:
        parser.error("--cargo-output is required")
    libs = parse_native_static_libs(pathlib.Path(args.cargo_output).read_text())

    if args.manifest:
        if not (
            args.snapshot_bin
            and args.snapshot_manifest
            and args.v8_component_manifest
            and args.build_metadata
        ):
            parser.error(
                "--manifest requires --snapshot-bin, --snapshot-manifest, "
                "--v8-component-manifest, and --build-metadata"
            )
        manifest_relative = f"share/migo/android-{android_abi}-manifest.json"
        artifacts = package_artifacts(
            prefix,
            exclude={manifest_relative},
        )
        snapshot = snapshot_identity(
            pathlib.Path(args.snapshot_bin),
            pathlib.Path(args.snapshot_manifest),
            args.arch,
        )
        v8 = v8_identity(pathlib.Path(args.v8_component_manifest), args.arch)
        if snapshot["v8_archive_hash"] != v8.get("hashes", {}).get("archive"):
            raise ValueError(
                "snapshot V8 archive hash does not match the packaged V8 component"
            )
        manifest = render_manifest(
            version=args.version,
            arch=args.arch,
            libs=libs,
            snapshot=snapshot,
            v8=v8,
            build_metadata=read_build_metadata(pathlib.Path(args.build_metadata)),
            artifacts=artifacts,
        )
        out_dir = prefix / "share" / "migo"
        out_dir.mkdir(parents=True, exist_ok=True)
        (prefix / manifest_relative).write_text(
            json.dumps(manifest, indent=2) + "\n")
        print(f"wrote artifact manifest under {out_dir}")
        return 0

    cmake_dir = prefix / "lib" / "cmake" / "migo"
    cmake_dir.mkdir(parents=True, exist_ok=True)
    (cmake_dir / "migo-config.cmake").write_text(render_cmake_config(args.version, libs))
    (cmake_dir / "migo-config-version.cmake").write_text(render_cmake_version(args.version))
    print(f"wrote CMake package metadata under {cmake_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
