#!/usr/bin/env python3
"""Generate the Android C ABI package's CMake integration and artifact manifest.

The Android package is cross-compiled and ships a static library the host links
into its own `.so`. Like the Linux generator, the consumer's link line is
derived from cargo's own `--print native-static-libs` rather than maintained by
hand, so it cannot drift from the build.

Every field the manifest records is checked against reality by
scripts/test-android-sdk-contract.sh; the manifest is a claim the gate verifies,
not documentation that drifts.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import pathlib
import re
import sys

_NOTE_RE = re.compile(r"native-static-libs:\s*(?P<libs>.+)")

# arch -> (android_abi, triple, cpu_baseline, required_cpu_features)
ARCH = {
    "aarch64": ("arm64-v8a", "aarch64-linux-android", "armv8-a", ["neon"]),
    "x86_64": ("x86_64", "x86_64-linux-android", "x86-64-v1", ["cmov", "sse2"]),
}
ANDROID_API_FLOOR = "26"


# The NDK clang driver links these automatically for a shared library or
# executable, and the C++ runtime it links is the consumer's own -DANDROID_STL
# choice. Recording them would over-link -- and listing both c++_static and
# c++_shared, as cargo's transitive note does, is contradictory: a consumer
# links exactly one STL. What the package records is only what a consumer must
# add on top of the toolchain: the platform libraries the archive references.
ANDROID_IMPLICIT_LIBS = {
    "c", "m", "dl", "unwind", "gcc", "gcc_eh",
    "c++_shared", "c++_static", "c++abi",
}


def parse_native_static_libs(text: str) -> list[str]:
    match = _NOTE_RE.search(text)
    if not match:
        raise ValueError("no 'native-static-libs:' note found in cargo output")
    seen: set[str] = set()
    libs: list[str] = []
    for token in match["libs"].split():
        # Only -l flags describe libraries the consumer must provide; drop the
        # absolute object paths cargo also lists for its own linking.
        if not token.startswith("-l"):
            continue
        name = token[2:]
        if name in ANDROID_IMPLICIT_LIBS:
            continue
        if token not in seen:
            seen.add(token)
            libs.append(token)
    if not libs:
        raise ValueError("no consumer-facing link libraries after filtering the toolchain set")
    return sorted(libs)


def sha256_file(path: pathlib.Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


def render_cmake_config(version: str, libs: list[str]) -> str:
    interface_libs = ";".join(lib[2:] for lib in libs if lib.startswith("-l"))
    return f"""\
# Generated by scripts/gen-android-package-metadata.py -- do not edit.
#
# Consume with the NDK toolchain:
#   cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake \\
#         -DANDROID_ABI=arm64-v8a -DANDROID_PLATFORM=android-{ANDROID_API_FLOOR} \\
#         -DCMAKE_PREFIX_PATH=<this package prefix> ...
cmake_minimum_required(VERSION 3.16)

get_filename_component(MIGO_PREFIX "${{CMAKE_CURRENT_LIST_DIR}}/../../.." ABSOLUTE)

set(MIGO_VERSION "{version}")
set(MIGO_INCLUDE_DIRS "${{MIGO_PREFIX}}/include")
set(MIGO_LIBRARY "${{MIGO_PREFIX}}/lib/libmigo_capi.a")

add_library(migo::migo STATIC IMPORTED)
set_target_properties(migo::migo PROPERTIES
    IMPORTED_LOCATION "${{MIGO_LIBRARY}}"
    INTERFACE_INCLUDE_DIRECTORIES "${{MIGO_INCLUDE_DIRS}}"
    INTERFACE_LINK_LIBRARIES "{interface_libs}")

set(migo_FOUND TRUE)
"""


def render_cmake_version(version: str) -> str:
    return f"""\
# Generated by scripts/gen-android-package-metadata.py -- do not edit.
set(PACKAGE_VERSION "{version}")
if(PACKAGE_VERSION VERSION_LESS PACKAGE_FIND_VERSION)
    set(PACKAGE_VERSION_COMPATIBLE FALSE)
else()
    set(PACKAGE_VERSION_COMPATIBLE TRUE)
    if(PACKAGE_VERSION VERSION_EQUAL PACKAGE_FIND_VERSION)
        set(PACKAGE_VERSION_EXACT TRUE)
    endif()
endif()
"""


def render_manifest(*, version, arch, libs, snapshot, v8, artifacts) -> dict:
    android_abi, triple, cpu_baseline, features = ARCH[arch]
    return {
        "schema": "migo-android-package-v1",
        "version": version,
        "os": "android",
        # Bionic userspace, not the Linux kernel it shares with glibc/OpenHarmony.
        "abi": "android",
        "arch": arch,
        "android_abi": android_abi,
        "target_triple": triple,
        "cpu_baseline": cpu_baseline,
        "required_cpu_features": sorted(features),
        "min_android_api": ANDROID_API_FLOOR,
        "link_libraries": libs,
        # Android always embeds a snapshot -- the js-runtime build embeds one per
        # ABI. "none" is a Linux-only policy.
        "snapshot_policy": "embedded",
        "snapshots": [snapshot],
        "v8": v8,
        "artifacts": artifacts,
    }


def _snapshot_identity(snapshot_bin: pathlib.Path, arch: str) -> dict:
    _, triple, _, _ = ARCH[arch]
    return {
        "runtime_kind": "host",
        "target_triple": triple,
        "arch": arch,
        # A normalized description of how the snapshot was produced, sorted so
        # comparisons are stable.
        "normalized_parameters": sorted([f"--arch={arch}", "--product-profile=full"]),
        "bytes_hash": sha256_file(snapshot_bin),
    }


def _v8_provenance(lock: pathlib.Path, arch: str) -> dict:
    data = json.loads(lock.read_text())
    _, triple, _, _ = ARCH[arch]
    return {
        "schema": "migo-v8-component-v1",
        "target": triple,
        "rusty_v8_revision": data["rusty_v8_revision"],
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--prefix", required=True, help="staged package prefix")
    parser.add_argument("--version", required=True)
    parser.add_argument("--arch", required=True, choices=sorted(ARCH))
    parser.add_argument("--cargo-output",
                        help="file holding the cargo --print native-static-libs output")
    parser.add_argument("--manifest", action="store_true",
                        help="write the artifact manifest instead of the CMake metadata")
    parser.add_argument("--snapshot-bin", help="embedded snapshot .bin (for --manifest)")
    parser.add_argument("--v8-lock",
                        help="contracts/artifact-manifest/android-v8.lock.json (for --manifest)")
    args = parser.parse_args()

    prefix = pathlib.Path(args.prefix)
    android_abi = ARCH[args.arch][0]

    if not args.cargo_output:
        parser.error("--cargo-output is required")
    libs = parse_native_static_libs(pathlib.Path(args.cargo_output).read_text())

    if args.manifest:
        if not (args.snapshot_bin and args.v8_lock):
            parser.error("--manifest requires --snapshot-bin and --v8-lock")
        artifacts = {
            path.name: path.stat().st_size
            for path in sorted((prefix / "lib").glob("libmigo_capi.a"))
            if path.is_file()
        }
        manifest = render_manifest(
            version=args.version,
            arch=args.arch,
            libs=libs,
            snapshot=_snapshot_identity(pathlib.Path(args.snapshot_bin), args.arch),
            v8=_v8_provenance(pathlib.Path(args.v8_lock), args.arch),
            artifacts=artifacts,
        )
        out_dir = prefix / "share" / "migo"
        out_dir.mkdir(parents=True, exist_ok=True)
        (out_dir / f"android-{android_abi}-manifest.json").write_text(
            json.dumps(manifest, indent=2) + "\n")
        print(f"wrote artifact manifest under {out_dir}")
        return 0

    cmake_dir = prefix / "lib" / "cmake" / "migo"
    cmake_dir.mkdir(parents=True, exist_ok=True)
    (cmake_dir / "migo-config.cmake").write_text(render_cmake_config(args.version, libs))
    (cmake_dir / "migo-config-version.cmake").write_text(render_cmake_version(args.version))
    print(f"wrote CMake package metadata under {cmake_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
